version: '3'
services:
  ### AWS services emulator
  aws:
    image: localstack/localstack
    environment:
      - SERVICES=s3:5000,sqs:5001
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=aws
    ports:
      - "5000:5000"
      - "5001:5001"
    network_mode: "host"

  ### Document generator service
  stream:
    build: ./stream
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: random
      AWS_SECRET_ACCESS_KEY: random
      AWS_REGION: us-east-1

  ### Microservice #1
  extract-text:
    build: ./services/extract-text
    command: ts-node-dev /server/src/index.ts
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: random
      AWS_SECRET_ACCESS_KEY: random
      AWS_REGION: us-east-1
    ports:
      - "5005:5005"
    volumes: 
      - ./services/extract-text/src:/server/src
    
  ### Microservice #2
  extract-image:
    build: ./services/extract-text
    command: ts-node-dev /server/src/index.ts
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: random
      AWS_SECRET_ACCESS_KEY: random
      AWS_REGION: us-east-1
    ports:
      - "5006:5006"
    volumes: 
      - ./services/extract-image/src:/server/src

  nats:
    image: nats
  